[tool.pytest.ini_options]
addopts = "-vv"
testpaths = [
    "tests",
]

[tool.black]
line-length = 160
# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#t-target-version
target-version = ["py38", "py39", "py310", "py311", "py312", "py313"]
include = '\.pyi?$'
