name: Create Flatpak

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
  # pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  flatpak:
    runs-on: ubuntu-24.04
    name: Flatpak

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        persist-credentials: false
    - name: Install Flatpak
      run: |
        sudo apt-get update
        sudo apt install flatpak flatpak-builder

    - name: Setup Flatpak
      run: |
        flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak install flathub org.gnome.Platform//50 org.gnome.Sdk//50 -y

    - name: Build Flatpak
      run: |
        flatpak-builder --repo=repo --force-clean build-dir .flatpak/io.github.GourmandRecipeManager.Gourmand.yml

    - name: Build Bundle
      run: |
        flatpak build-bundle repo gourmand-${GITHUB_SHA::8}.flatpak io.github.GourmandRecipeManager.Gourmand

    - name: Upload Flatpak
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: gourmand.flatpak
        archive: false
        path: ./gourmand-*.flatpak
